[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.3.1"
  export = ["risk"]
  icon = "docs/icon.png"
  keywords = ["Kind/Sample","Type/RestApi","Category/Service","Internal/http"]
  name = "risk"
  org = "cradle"
  version = "3.1.0"

